Invoke-Sqlcmd -InputFile DropDataBase.sql
Invoke-Sqlcmd -InputFile ToDo.sql
Invoke-Sqlcmd -InputFile Account.sql
Invoke-Sqlcmd -InputFile TodoLists.sql
Invoke-Sqlcmd -InputFile TodoListItems.sql
Invoke-Sqlcmd -InputFile TodoListLayouts.sql
Invoke-Sqlcmd -InputFile SubItems.sql
Invoke-Sqlcmd -InputFile SubItemLayouts.sql
Invoke-Sqlcmd -InputFile TestingDataScript.sql
