USE [ToDo]

GO

CREATE TABLE [SubItems](
    [ID] INT PRIMARY KEY IDENTITY(1,1),
    [ListItemID] INT,
    [Name] VARCHAR(50),
    [Completed] BIT NOT NULL DEFAULT(0)

    FOREIGN KEY (ListItemID) REFERENCES TodoListItems (ID) ON DELETE CASCADE
)

GO