USE [ToDo]

GO

CREATE TABLE [TodoLists](
    [ID] UNIQUEIDENTIFIER PRIMARY KEY,
    [ListTitle] VARCHAR(50) NOT NULL,
    [AccountID] UNIQUEIDENTIFIER,
    [Completed] BIT NOT NULL DEFAULT(0),

    FOREIGN KEY (AccountID)
    REFERENCES Accounts (ID) ON DELETE CASCADE
)

GO